<center><img SRC="CR.png"/></center> 

<center><h1 style="color:#00FFFF"> Analisis de datos </h1></center>
<center><h4 style="color:#6495ED"> U.Castro Carazo </h5></center>
<center><h6 style="color:#6495ED"> II Cuatrimestre </h6></center>
</br>
</br>
<p Style="text-aling: justify">La empresa PK2, especialista en venta de vehiculos usados, desea conocer cual es la distribucion y costo de los autos que tienen actualmente en inventario, para la venta.

La pregunta de negocio para responder es: ¿cual es estrategia podria implementar para generar una mayor rotacionde inventario?
    
El objetivo principal, es poder proponer una estrategia de venta de carros en funcion de los disponibles en el lote actual.</p>

<!-- para escribir comentarios -->
<p style = "font-weight:bold"> la fuente para cambiar los colores del texto es:</p> 
<a href="https://www.w3schools.com/html/html_links.asp">W3SCHOOLS</a>

# <h2 style="color:#FF7F50">1. Carga y estandarizacion de los archivos de datos </h2>  

<p style="color:#FF7F50">
<p style="font-weight: bold"> Que se hace en este apartado? </p></p>

<ol style="list-style-type:lower-alpha">
    <li>Importar las librerias a utilizar </li>
    <li>Importar los set de datos (XLSX, CSV, TXT, SQL, ORACLE) </li>
    <li>Revision de los nombres de las columnas del set de datos</li>
    <li>si tenemos mas de 1 archivo, vamos a unirlos en un unico datafreame </li>
</ol>

<h3 style="color:#B8860B">a. Importar las librerias a utilizar</h3>

In [6]:
#Se realiza las importaciones de las librerias necesarias para el ejerecicio de analisis de datos, sobre los autos disponibles.

import pandas as pd             #para manejo de los datos -DataFrame-
import numpy as np              #para el manejo de estructuras de datos -Listas_
import matplotlib.pyplot as plt #para la creacion de los graficos

In [ ]:
# df_nombvariable
# df_nombvariable.head(n)                            = Devuelve las n primeras filas del DataFrame df  
# df_nombvariable.shape                              = Devuelve una tupla con el número de filas y columnas del DataFrame
# df_nombvariable.columns                            = Devuelve una tupla con el número de filas y columnas del DataFrame
# df_nombvariable.tail(n)                            = Devuelve las n últimas filas del DataFrame
# df_nombvariable.describe()                         = Devuelve un DataFrame con un resumen estadístico de las columnas 
# df_nombvariable.info()                             = Devuelve información (número de filas, número de columnas, índices, tipo de las columnas y memoria usado) sobre el DataFrame
# unionArchivos = [df_nombvariable1, df_nombvariable2] = creacion de una lista de dos set de datos
# df_nuevaVarialbe = pd.concat(unionArchivos)          = luego de la creacion de las listas se procede a unir los dos set de datos

<h3 style="color:#B8860B">b. Importar el Set de datos</h3>

<p Style="color:#6A5ACD">La fuente de los datos es la pagina denominada Machine Learning Repository, en esta se puede obtener el nombre de los encabezados del set de datos. </p>

<a href="https://archive.ics.uci.edu/ml/datasets/Automobile">Fuente de datos</a>

In [12]:
#Se crea una lista con los nombres de las columnas.
cols = ["symboling", "normalized", "make", "fuel", "aspiration", "doors",
"style", "wheels", "engine", "base", "length", "width", "heingt",
"curb", "engineType", "Cylinders", "engine-size", "system", "bore", "stroke",
"compression", "horsepower", "peak", "City", "Higway", "price" ]

#Se cargan los set de datos en la memoria de la PC.
df_autos1 = pd.read_csv("autos1.csv", names = cols)
df_autos2 = pd.read_csv("autos.csv", names = cols)

In [8]:
df_autos1

,symboling,normalized,make,fuel,aspiration,doors,style,wheels,engine,base,...,engine-size,system,bore,stroke,compression,horsepower,peak,City,Higway,price
0,0,106,nissan,gas,std,four,sedan,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549
1,0,128,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,13499
2,0,108,nissan,gas,std,four,wagon,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,14399
3,0,108,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,19,25,13499
4,3,194,nissan,gas,std,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,17199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,0,?,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.0,68,4500,33,38,13845
93,0,?,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.40,9.0,88,5500,25,31,12290
94,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,12940
95,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
96,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985

In [9]:
df_autos1.head(10)

,symboling,normalized,make,fuel,aspiration,doors,style,wheels,engine,base,...,engine-size,system,bore,stroke,compression,horsepower,peak,City,Higway,price
0,0,106,nissan,gas,std,four,sedan,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549
1,0,128,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,13499
2,0,108,nissan,gas,std,four,wagon,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,14399
3,0,108,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,19,25,13499
4,3,194,nissan,gas,std,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,17199
5,3,194,nissan,gas,turbo,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,7.8,200,5200,17,23,19699
6,1,231,nissan,gas,std,two,hatchback,rwd,front,99.2,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,18399
7,0,161,peugot,gas,std,four,sedan,rwd,front,107.9,...,120,mpfi,3.46,3.19,8.4,97,5000,19,24,11900
8,0,161,peugot,diesel,turbo,four,sedan,rwd,front,107.9,...,152,idi,3.70,3.52,21.0,95,4150,28,33,13200
9,0,?,peugot,gas,std,four,wagon,rwd,front,114.2,...,120,mpfi,3.46,3.19,8.4,97,5000,19,24,12440

In [11]:
df_autos2

,symboling,normalized,make,fuel,aspiration,doors,style,wheels,engine,base,...,engine-size,system,bore,stroke,compression,horsepower,peak,City,Higway,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,0,?,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.0,68,4500,33,38,13845
193,0,?,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.40,9.0,88,5500,25,31,12290
194,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,12940
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985

In [14]:
df_autos2.head(10)

,symboling,normalized,make,fuel,aspiration,doors,style,wheels,engine,base,...,engine-size,system,bore,stroke,compression,horsepower,peak,City,Higway,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,?

In [16]:
df_autos1.shape

(97, 26)

In [17]:
df_autos2.shape

(197, 26)

<h3 style="color:#B8860B">c. Revision las columnas</h3>
Este Comando permite consultar los nombres de las Columnas

In [22]:
df_autos2.columns

Index(['symboling', 'normalized', 'make', 'fuel', 'aspiration', 'doors',
       'style', 'wheels', 'engine', 'base', 'length', 'width', 'heingt',
       'curb', 'engineType', 'Cylinders', 'engine-size', 'system', 'bore',
       'stroke', 'compression', 'horsepower', 'peak', 'City', 'Higway',
       'price'],
      dtype='object')

In [24]:
df_autos1.columns

Index(['symboling', 'normalized', 'make', 'fuel', 'aspiration', 'doors',
       'style', 'wheels', 'engine', 'base', 'length', 'width', 'heingt',
       'curb', 'engineType', 'Cylinders', 'engine-size', 'system', 'bore',
       'stroke', 'compression', 'horsepower', 'peak', 'City', 'Higway',
       'price'],
      dtype='object')

In [44]:
df_autos1.head(15)  #las consultas se hacen entre las primeras 15 o 30 filas

,symboling,normalized,make,fuel,aspiration,doors,style,wheels,engine,base,...,engine-size,system,bore,stroke,compression,horsepower,peak,City,Higway,price
0,0,106,nissan,gas,std,four,sedan,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549
1,0,128,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,13499
2,0,108,nissan,gas,std,four,wagon,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,17,22,14399
3,0,108,nissan,gas,std,four,sedan,fwd,front,100.4,...,181,mpfi,3.43,3.27,9.0,152,5200,19,25,13499
4,3,194,nissan,gas,std,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,17199
5,3,194,nissan,gas,turbo,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,7.8,200,5200,17,23,19699
6,1,231,nissan,gas,std,two,hatchback,rwd,front,99.2,...,181,mpfi,3.43,3.27,9.0,160,5200,19,25,18399
7,0,161,peugot,gas,std,four,sedan,rwd,front,107.9,...,120,mpfi,3.46,3.19,8.4,97,5000,19,24,11900
8,0,161,peugot,diesel,turbo,four,sedan,rwd,front,107.9,...,152,idi,3.70,3.52,21.0,95,4150,28,33,13200
9,0,?,peugot,gas,std,four,wagon,rwd,front,114.2,...,120,mpfi,3.46,3.19,8.4,97,5000,19,24,12440
10,0,?,peugot,diesel,turbo,four,wagon,rwd,front,114.2,...,152,idi,3.70,3.52,21.0,95,4150,25,25,13860
11,0,161,peugot,gas,std,four,sedan,rwd,front,107.9,...,120,mpfi,3.46,2.19,8.4,95,5000,19,24,15580
12,0,161,peugot,diesel,turbo,four,sedan,rwd,front,107.9,...,152,idi,3.70,3.52,21.0,95,4150,28,33,16900
13,0,?,peugot,gas,std,four,wagon,rwd,front,114.2,...,120,mpfi,3.46,2.19,8.4,95,5000,19,24,16695
14,0,?,peugot,diesel,turbo,four,wagon,rwd,front,114.2,...,152,idi,3.70,3.52,21.0,95,4150,25,25,17075

In [ ]:
#1 - lo primero que se debe de hacer en la revision es verificar si lo registrado en cada columna corresponde al tipo 
#  de dato que tenemos segun la meta data.

<h3 style="color:#E9967A">Revision y Validadion de las Variables</h3>
<p>Este proceso de revision permite identificar variables o datos que deben ser analizados de manera independiente ya que no concuerdan con el rango de inforamcion a contener.</p>

<center><p style="color:#F0E68C" >Se requiere como insumo disponer de los Meta Datos</p></center>
</br>

In [57]:
df_autos1.tail(10)  # Busca los ultimos 10 registros

,symboling,normalized,make,fuel,aspiration,doors,style,wheels,engine,base,...,engine-size,system,bore,stroke,compression,horsepower,peak,City,Higway,price
87,2,94,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,68,4500,37,42,9495
88,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,10.0,100,5500,26,32,9995
89,3,?,volkswagen,gas,std,two,convertible,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.5,90,5500,24,29,11595
90,3,256,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.5,90,5500,24,29,9980
91,0,?,volkswagen,gas,std,four,sedan,fwd,front,100.4,...,136,mpfi,3.19,3.40,8.5,110,5500,19,24,13295
92,0,?,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.0,68,4500,33,38,13845
93,0,?,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.40,9.0,88,5500,25,31,12290
94,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,12940
95,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
96,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985

In [46]:
#Todos los datos NUMERICO nos sirve para darnos Estadisticas Descriptivas

In [48]:
df_autos1.describe()

,symboling,base,length,width,heingt,curb,engine-size,bore,stroke,compression,City,Higway
count,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000
mean,0.855670,98.823711,175.208247,65.872165,54.194845,2587.175258,125.432990,3.388969,3.169381,10.570206,25.185567,30.814433
std,1.314896,5.332170,10.064062,1.655719,2.416755,412.305914,29.560992,0.264412,0.352691,4.373831,5.470241,5.784912
min,-2.000000,89.500000,156.900000,63.400000,49.700000,1918.000000,90.000000,2.540000,2.070000,7.000000,17.000000,22.000000
25%,0.000000,95.700000,168.900000,64.400000,52.500000,2261.000000,98.000000,3.190000,3.030000,9.000000,20.000000,25.000000
50%,0.000000,97.300000,173.500000,65.600000,54.500000,2535.000000,120.000000,3.430000,3.230000,9.000000,25.000000,30.000000
75%,2.000000,100.400000,183.500000,66.600000,56.000000,2975.000000,146.000000,3.620000,3.400000,9.400000,28.000000,34.000000
max,3.000000,114.200000,198.900000,72.300000,59.800000,3485.000000,203.000000,3.940000,3.900000,23.000000,38.000000,47.000000

In [49]:
# Count = cantidad de registros que el campo pudo contar
# mean  =
# std   =
# min   = Valor minimo
# 25%   =
# 50%   =
# 75%   =
# max   = Valor minimo

In [50]:
#para saber como las cargo python
df_autos1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 26 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   symboling    97 non-null     int64
 1   normalized   97 non-null     object
 2   make         97 non-null     object
 3   fuel         97 non-null     object
 4   aspiration   97 non-null     object
 5   doors        97 non-null     object
 6   style        97 non-null     object
 7   wheels       97 non-null     object
 8   engine       97 non-null     object
 9   base         97 non-null     float64
 10  length       97 non-null     float64
 11  width        97 non-null     float64
 12  heingt       97 non-null     float64
 13  curb         97 non-null     int64
 14  engineType   97 non-null     object
 15  Cylinders    97 non-null     object
 16  engine-size  97 non-null     int64
 17  system       97 non-null     object
 18  bore         97 non-null     float64
 19  stroke       97 non-null     float64
 20  compression  97 non-null     float64
 21  horsepower   97 non-null     object
 22  peak         97 non-null     object
 23  City         97 non-null     int64
 24  Higway       97 non-null     int64
 25  price        97 non-null     object
dtypes: float64(7), int64(5), object(14)
memory usage: 19.8+ KB

<h3 style="color:#B8860B"> d. Unir los Set de datos </h3>

In [60]:
# df_autos1 - 97 observaciones y 26 columnas
# df_autos2 - 197 observaciones y 26 columnas
# para poder unir dos set de datos es importante que el numero de columnas sean iguales

unionArchivos = [df_autos1, df_autos2] #se esta creando una lista del dataframe
df_Autos = pd.concat(unionArchivos)    #creacion de la nueva variable utilizando concat(concatenar)
df_Autos.shape

(294, 26)

# <h2 style="color:#FF7F50">2. Manejo de Varlores Faltantes </h2>  

<p style="color:#FF7F50">
<p style="font-weight: bold"> Que se hace en este apartado? </p></p>

<ol>
    <li>Identificar como se muestras los valores faltantes y estandarizarlos a Nan </li>
    <li>Contar la cantidad de valores NaN (faltantes)</li>
    <li>Analisis para imputar los Valores numericos con la media </li>
    <li>Analisis para imputar los Valores caracter como el mas frecuente</li>
    <li>Eliminar filas con valores faltantes</li>
</ol>

<h3 style="color:#B8860B">1. Identificar como se muestras los valores faltantes y estandarizarlos a Nan</h3>